/* Shared contract between the per-build shader registry (generated by the compiler, see
 * codegen/gpu_embed.c) and the in-binary Vulkan dispatcher (runtime/gpu_runtime.c). A `--gpu`
 * build embeds one ArcheGpuShader per `@gpu` map (its SPIR-V) and links both objects; codegen
 * emits `arche_gpu_dispatch(...)` calls that fall back to the CPU path on any nonzero return. */
#ifndef ARCHE_GPU_H
#define ARCHE_GPU_H

#include <stddef.h>

/* One embedded compute shader: the SPIR-V for a `@gpu` map plus its column (SSBO) count. */
typedef struct {
	const char *name;         /* the map's name — the dispatch lookup key */
	const unsigned char *spv; /* SPIR-V words as little-endian bytes */
	size_t spv_len;           /* byte length (a multiple of 4) */
	unsigned ncol;            /* number of column buffers, bound at binding 0..ncol-1 */
} ArcheGpuShader;

/* Resolve a map name to its embedded shader. Provided by the generated registry object (one per
 * build). Returns NULL when no `@gpu` shader was embedded for `name` (→ CPU fallback). */
const ArcheGpuShader *arche_gpu_lookup(const char *name);

/* Run map `name` on the GPU over `ncol` columns of `count` elements (`elem_size` bytes each).
 * `resident == 0`: host buffers in `cols[]` are uploaded, the kernel runs, results are read back into
 * the same buffers, device buffers freed (per-dispatch model).
 * `resident == 1`: device buffers persist across dispatches in a host-pointer-keyed cache — uploaded
 * once on first sight, reused (no re-upload) and NOT downloaded; the host copy stays stale until
 * `arche_gpu_sync`. Returns 0 on success (ran on GPU), nonzero on ANY failure — the caller then runs
 * the CPU path, so a missing device / driver / shader is always safe. Provided by gpu_runtime.c. */
int arche_gpu_dispatch(const char *name, unsigned ncol, void **cols, unsigned elem_size, unsigned count,
                       int resident);

/* Download resident device buffers back to host (the explicit GPU->CPU sync for a `gpu.sync(Pool)`
 * schedule leaf). For each `cols[b]` that is a dirty resident buffer, copies device data back and clears
 * the dirty flag. No-op for non-resident cols and in the no-Vulkan build. Provided by gpu_runtime.c. */
void arche_gpu_sync(void **cols, unsigned ncol, unsigned elem_size, unsigned count);

#endif
