/* Arche extern-type handle table runtime helpers.
 *
 * These are the definitions that back the `declare` stubs emitted by codegen
 * for each `extern type T(N)` declaration.  Previously these were static
 * inline in handles.h; they are now non-inline so that LLVM IR generated by
 * the compiler can reference them as external symbols and link against this
 * object file.
 */

#define _POSIX_C_SOURCE 200809L
#include "handles.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

int32_t __arche_slot_alloc(const char *type_name,
                           __ArcheSlot *slots,
                           int capacity,
                           void *ptr)
{
    for (int i = 0; i < capacity; i++) {
        if (!slots[i].in_use) {
            slots[i].ptr = ptr;
            slots[i].in_use = 1;
            return (int32_t)(((uint32_t)slots[i].gen << 16) | (uint32_t)(i + 1));
        }
    }
    fprintf(stderr,
            "arche fatal: capacity exhausted (type=%s capacity=%d)\n",
            type_name, capacity);
    abort();
}

void *__arche_slot_get(const char *type_name,
                       __ArcheSlot *slots,
                       int capacity,
                       int32_t handle)
{
    if (handle == 0) {
        fprintf(stderr, "arche fatal: null handle (type=%s)\n", type_name);
        abort();
    }
    uint16_t gen      = (uint16_t)((uint32_t)handle >> 16);
    uint16_t slot_p1  = (uint16_t)((uint32_t)handle & 0xFFFFu);
    if (slot_p1 == 0 || slot_p1 > (uint16_t)capacity) {
        fprintf(stderr,
                "arche fatal: slot out of range (type=%s handle=0x%08x slot=%u capacity=%d)\n",
                type_name, (unsigned)(uint32_t)handle, slot_p1, capacity);
        abort();
    }
    int idx = slot_p1 - 1;
    if (!slots[idx].in_use) {
        fprintf(stderr,
                "arche fatal: freed slot (type=%s handle=0x%08x slot=%d)\n",
                type_name, (unsigned)(uint32_t)handle, idx);
        abort();
    }
    if (slots[idx].gen != gen) {
        fprintf(stderr,
                "arche fatal: stale generation (type=%s handle=0x%08x slot=%d expected=%u got=%u)\n",
                type_name, (unsigned)(uint32_t)handle, idx,
                (unsigned)slots[idx].gen, (unsigned)gen);
        abort();
    }
    return slots[idx].ptr;
}

void __arche_slot_free(const char *type_name,
                       __ArcheSlot *slots,
                       int capacity,
                       int32_t handle)
{
    (void)type_name;
    if (handle == 0) return;
    uint16_t slot_p1 = (uint16_t)((uint32_t)handle & 0xFFFFu);
    if (slot_p1 == 0 || slot_p1 > (uint16_t)capacity) return;
    int idx = slot_p1 - 1;
    slots[idx].in_use = 0;
    slots[idx].ptr = NULL;
    slots[idx].gen++;
}
