#include "args.h"
#include "cli.h"
#include <stdio.h>
#include <string.h>

/* `arche completion <bash|zsh|fish>` — print a static completion script generated from the live
 * dispatch table (cli_commands) and each command's ArgSpec table (cmd->specs), so the completions
 * track the CLI automatically. Subcommands complete at the first position; each subcommand's flags
 * complete after it; file arguments fall through to the shell's default file completion. */

/* Print every accepted spelling in a command's spec table (non-hidden), space-separated, to `f`. */
static void print_flags(FILE *f, const ArgSpec *specs) {
	if (!specs)
		return;
	for (const ArgSpec *s = specs; s->id != 0; s++) {
		if (s->hidden)
			continue;
		fprintf(f, "%s ", s->forms); /* `forms` is already space-separated spellings */
	}
}

static void emit_bash(FILE *f) {
	int n;
	const SubCmd *cmds = cli_commands(&n);
	fprintf(f, "# bash completion for arche — generated by `arche completion bash`\n");
	fprintf(f, "_arche() {\n");
	fprintf(f, "  local cur prev cmds sub\n");
	fprintf(f, "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n");
	fprintf(f, "  cmds=\"");
	for (int i = 0; i < n; i++)
		if (!cmds[i].hidden)
			fprintf(f, "%s ", cmds[i].name);
	fprintf(f, "help\"\n");
	fprintf(f, "  if [ \"$COMP_CWORD\" -eq 1 ]; then\n");
	fprintf(f, "    COMPREPLY=( $(compgen -W \"$cmds\" -- \"$cur\") )\n");
	fprintf(f, "    return\n");
	fprintf(f, "  fi\n");
	fprintf(f, "  sub=\"${COMP_WORDS[1]}\"\n");
	fprintf(f, "  case \"$sub\" in\n");
	for (int i = 0; i < n; i++) {
		if (cmds[i].hidden)
			continue;
		const ArgSpec *specs = cmds[i].specs ? cmds[i].specs() : NULL;
		fprintf(f, "    %s) COMPREPLY=( $(compgen -W \"", cmds[i].name);
		print_flags(f, specs);
		fprintf(f, "--help\" -- \"$cur\") $(compgen -f -- \"$cur\") );;\n");
	}
	fprintf(f, "    *) COMPREPLY=( $(compgen -f -- \"$cur\") );;\n");
	fprintf(f, "  esac\n");
	fprintf(f, "}\n");
	fprintf(f, "complete -F _arche arche\n");
}

static void emit_zsh(FILE *f) {
	int n;
	const SubCmd *cmds = cli_commands(&n);
	fprintf(f, "#compdef arche\n");
	fprintf(f, "# zsh completion for arche — generated by `arche completion zsh`\n");
	fprintf(f, "_arche() {\n");
	fprintf(f, "  local -a cmds\n");
	fprintf(f, "  cmds=(");
	for (int i = 0; i < n; i++)
		if (!cmds[i].hidden)
			fprintf(f, "%s ", cmds[i].name);
	fprintf(f, "help)\n");
	fprintf(f, "  if (( CURRENT == 2 )); then\n");
	fprintf(f, "    compadd -- $cmds\n");
	fprintf(f, "    return\n");
	fprintf(f, "  fi\n");
	fprintf(f, "  case ${words[2]} in\n");
	for (int i = 0; i < n; i++) {
		if (cmds[i].hidden)
			continue;
		const ArgSpec *specs = cmds[i].specs ? cmds[i].specs() : NULL;
		fprintf(f, "    %s) compadd -- ", cmds[i].name);
		print_flags(f, specs);
		fprintf(f, "--help; _files;;\n");
	}
	fprintf(f, "    *) _files;;\n");
	fprintf(f, "  esac\n");
	fprintf(f, "}\n");
	fprintf(f, "_arche \"$@\"\n");
}

static void emit_fish(FILE *f) {
	int n;
	const SubCmd *cmds = cli_commands(&n);
	fprintf(f, "# fish completion for arche — generated by `arche completion fish`\n");
	fprintf(f, "complete -c arche -f\n");
	/* subcommands, only when no subcommand has been typed yet */
	for (int i = 0; i < n; i++) {
		if (cmds[i].hidden)
			continue;
		fprintf(f, "complete -c arche -n __fish_use_subcommand -a %s -d '%s'\n", cmds[i].name, cmds[i].summary);
	}
	/* per-subcommand flags: emit only `--long` flags (fish's native long-option form) */
	for (int i = 0; i < n; i++) {
		if (cmds[i].hidden || !cmds[i].specs)
			continue;
		const ArgSpec *specs = cmds[i].specs();
		for (const ArgSpec *s = specs; s->id != 0; s++) {
			if (s->hidden)
				continue;
			/* take each space-separated spelling; only `--xxx` maps cleanly to fish -l */
			const char *p = s->forms;
			while (*p) {
				while (*p == ' ')
					p++;
				const char *start = p;
				while (*p && *p != ' ')
					p++;
				size_t len = (size_t)(p - start);
				if (len > 2 && start[0] == '-' && start[1] == '-')
					fprintf(f, "complete -c arche -n '__fish_seen_subcommand_from %s' -l %.*s -d '%s'\n",
					        cmds[i].name, (int)(len - 2), start + 2, s->help ? s->help : "");
			}
		}
	}
}

int completion_run(int argc, char **argv, const GlobalOpts *g) {
	(void)g;
	(void)argc;
	/* argv[1] (if present) is the shell name. */
	const char *shell = (argc >= 2) ? argv[1] : NULL;
	if (!shell || strcmp(shell, "--help") == 0 || strcmp(shell, "-h") == 0) {
		fprintf(shell ? stdout : stderr, "usage: %s completion <bash|zsh|fish>\n", g_prog);
		return shell ? ARCHE_OK : ARCHE_USAGE;
	}
	if (strcmp(shell, "bash") == 0)
		emit_bash(stdout);
	else if (strcmp(shell, "zsh") == 0)
		emit_zsh(stdout);
	else if (strcmp(shell, "fish") == 0)
		emit_fish(stdout);
	else {
		fprintf(stderr, "%s: unknown shell '%s' (want: bash, zsh, fish)\n", g_prog, shell);
		return ARCHE_USAGE;
	}
	return ARCHE_OK;
}
